before_script:
  - bash scripts/docker_install.sh > /dev/null
  - curl --silent --show-error https://getcomposer.org/installer | php
  - php composer.phar install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test

test:5.5:
  image: php:5.5
  script:
  - vendor/bin/simple-phpunit

test:5.6:
  image: php:5.6
  script:
  - vendor/bin/simple-phpunit

test:7.0:
  image: php:7.0
  script:
  - vendor/bin/simple-phpunit

test:7.1:
  image: php:7.1
  script:
  - vendor/bin/simple-phpunit
