# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
            AppBundle\Service\MenuBuilderInterface:
                tags: [app.menu]

    app.menu_builders_chain:
        class: AppBundle\Service\MenuBuilderChain

    AppBundle\Service\CoreMenu: ~

    AppBundle\Service\CoreData: ~

    AppBundle\Service\MailerService:
        autowire: false
        arguments: ["%notification.prefix%", "%notification.email_from%", "@mailer", "@translator"]

    AppBundle\Listener\SecurityListener: ~

    AppBundle\Listener\RequestListener: ~

    AppBundle\Service\UserExtensionService: ~

    AppBundle\Security\OrganizationVoter: ~
