# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
            AppBundle\Service\MenuBuilderInterface:
                tags: [app.menu]

    # makes classes in src/AppBundle available to be used as services
    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Utils,DoctrineExtensions,Migrations}'

    app.menu_builders_chain:
        class: AppBundle\Service\MenuBuilderChain

    AppBundle\Service\MailerService:
        autowire: false
        arguments: ["%notification.prefix%", "%notification.email_from%", "@mailer", "@translator"]

    AppBundle\Service\SenecaAuthenticatorService:
        autowire: false
        arguments: ["%external.url%", "%external.url.force_security%", "%external.enabled%"]
